const coordinates = [
  // {
  //   id: 8,
  //   ltd: 47.213534,
  //   lng: 38.928277,
  //   desc: "Таганрогский историко-краеведческий музей",
  //   pathId: 2,
  //   address: "ул. Фрунзе, 41",
  //   createdAt: "NOW();",
  //   updatedAt: "NOW();",
  //   UserId: 1,
  // },
  // {
  //   id: 9,
  //   ltd: 47.212187,
  //   lng: 38.926813,
  //   desc: "Таганрогский художественный музей",
  //   pathId: 2,
  //   address: "Лермонтовский переулок, 22",
  //   createdAt: "NOW();",
  //   updatedAt: "NOW();",
  //   UserId: 1,
  // },
  // {
  //   id: 10,
  //   ltd: 47.210179,
  //   lng: 38.930721,
  //   desc: "Таганрогская художественная галерея",
  //   pathId: 2,
  //   address: "Александровская ул., 56",
  //   createdAt: "NOW();",
  //   updatedAt: "NOW();",
  //   UserId: 1,
  // },
  // {
  //   id: 11,
  //   ltd: 47.209775,
  //   lng: 38.925528,
  //   desc: "Дом-музей писателя И.Д. Василенко",
  //   pathId: 2,
  //   address: "ул. Чехова, 88",
  //   createdAt: "NOW();",
  //   updatedAt: "NOW();",
  //   UserId: 1,
  // },
  // {
  //   id: 12,
  //   ltd: 47.209176,
  //   lng: 38.922762,
  //   desc: "Музей А.А. Дурова",
  //   pathId: 2,
  //   address: "пер. Антона Глушко, 44",
  //   createdAt: "NOW();",
  //   updatedAt: "NOW();",
  //   UserId: 1,
  // },
  // {
  //   id: 13,
  //   ltd: 47.212181,
  //   lng: 38.938419,
  //   desc: "Мемориальный Домик П. И. Чайковского",
  //   pathId: 2,
  //   address: "Греческая ул., 56",
  //   createdAt: "NOW();",
  //   updatedAt: "NOW();",
  //   UserId: 1,
  // },
  // {
  //   id: 14,
  //   ltd: 47.205747,
  //   lng: 38.939048,
  //   desc: "Политехнический музей ИТА ЮФУ",
  //   pathId: 2,
  //   address: "ул. Чехова, 22Б",
  //   createdAt: "NOW();",
  //   updatedAt: "NOW();",
  //   UserId: 1,
  // },
  // {
  //   id: 15,
  //   ltd: 47.222910,
  //   lng: 38.934197,
  //   desc: "Таганрогский военно-исторический музей",
  //   pathId: 2,
  //   address: "ул. Лесная Биржа, 20Б",
  //   createdAt: "NOW();",
  //   updatedAt: "NOW();",
  //   UserId: 1,
  // }
  {
    id: 16,
    ltd: 47.219550,
    lng: 38.938141,
    desc: "Greenwich Park",
    pathId: 3,
    address: "улица Адмирала Крюйса, 2А",
    createdAt: "NOW();",
    updatedAt: "NOW();",
    UserId: 1,
  },
  {
    id: 17,
    ltd: 47.202442,
    lng: 38.895677,
    desc: "Приморский парк",
    pathId: 3,
    address: "Инструментальная улица, 15А",
    createdAt: "NOW();",
    updatedAt: "NOW();",
    UserId: 1,
  },
  {
    id: 18,
    ltd: 47.218645,
    lng: 38.924334,
    desc: "Парк Культуры и отдыха имени Горького",
    pathId: 3,
    address: "Петровская улица, 104А",
    createdAt: "NOW();",
    updatedAt: "NOW();",
    UserId: 1,
  },
  {
    id: 19,
    ltd: 47.250479, 
    lng: 38.917399,
    desc: "Кино-Нео",
    pathId: 3,
    address: "ул. Дзержинского, 161-4",
    createdAt: "NOW();",
    updatedAt: "NOW();",
    UserId: 1,
  },
  {
    id: 20,
    ltd: 47.250479, 
    lng: 38.917399,
    desc: "Кино-Нео",
    pathId: 3,
    address: "ул. Дзержинского, 161-4",
    createdAt: "NOW();",
    updatedAt: "NOW();",
    UserId: 1,
  },
  {
    id: 21,
    ltd: 47.244564, 
    lng: 38.891006,
    desc: "В Облака (батутный центр)",
    pathId: 3,
    address: "Большая Бульварная ул., 13",
    createdAt: "NOW();",
    updatedAt: "NOW();",
    UserId: 1,
  },
  {
    id: 22,
    ltd: 47.217482,
    lng: 38.898857,
    desc: "Мармелад (ТРЦ)",
    pathId: 3,
    address: "площадь Мира, 7",
    createdAt: "NOW();",
    updatedAt: "NOW();",
    UserId: 1,
  },
  {
    id: 23,
    ltd: 47.204664, 
    lng: 38.945175,
    desc: "Сквер Петра I",
    pathId: 3,
    address: "Греческая улица, 2",
    createdAt: "NOW();",
    updatedAt: "NOW();",
    UserId: 1,
  },
  {
    id: 24,
    ltd: 47.206794, 
    lng: 38.938563,
    desc: "Студенческий сквер IT-Агора",
    pathId: 3,
    address: "Некрасовский пер., 21",
    createdAt: "NOW();",
    updatedAt: "NOW();",
    UserId: 1,
  },
];
