let i = [
  {
    id: 37,
    ltd: 47.209149,
    lng: 38.935939,
    desc: "Октябрьская площадь",
    pathId: 6,
    address: "Октябрьская площадь",
    review: null,
    isPrivate: false,
    createdAt: "NOW()",
    updatedAt: "NOW()",
    userId: 0,
  },
  {
    id: 38,
    ltd: 47.22286,
    lng: 38.85578,
    desc: "Парк Имени 300-летия Города Таганрога",
    pathId: 6,
    address: "ул. Сергея Шило, 210",
    review: null,
    isPrivate: false,
    createdAt: "NOW()",
    updatedAt: "NOW()",
    userId: 0,
  },
  {
    id: 39,
    ltd: 47.211869,
    lng: 38.933541,
    desc: "Европейский квартал",
    pathId: 6,
    address: "ул. Петровская, 51",
    review: null,
    isPrivate: false,
    createdAt: "NOW()",
    updatedAt: "NOW()",
    userId: 0,
  },
  {
    id: 40,
    ltd: 47.199956,
    lng: 38.938752,
    desc: "Богудония",
    pathId: 6,
    address: "поселок Богудония",
    review: null,
    isPrivate: false,
    createdAt: "NOW()",
    updatedAt: "NOW()",
    userId: 0,
  },
  {
    id: 41,
    ltd: 47.199837,
    lng: 38.895979,
    desc: "Приморский парк",
    pathId: 6,
    address: "Приморский парк",
    review: null,
    isPrivate: false,
    createdAt: "NOW()",
    updatedAt: "NOW()",
    userId: 0,
  },
  {
    id: 42,
    ltd: 47.214244,
    lng: 38.940111,
    desc: "Пушкинская набережная",
    pathId: 6,
    address: "Пушкинская набережная",
    review: null,
    isPrivate: false,
    createdAt: "NOW()",
    updatedAt: "NOW()",
    userId: 0,
  },
  {
    id: 43,
    ltd: 47.218571,
    lng: 38.925395,
    desc: "Парк Культуры и отдыха имени Горького",
    pathId: 6,
    address: "Парк Культуры и отдыха имени Горького",
    review: null,
    isPrivate: false,
    createdAt: "NOW()",
    updatedAt: "NOW()",
    userId: 0,
  },
  {
    id: 44,
    ltd: 47.21306,
    lng: 38.938122,
    desc: "Каменная лестница",
    pathId: 6,
    address: "квартал Центр",
    review: null,
    isPrivate: false,
    createdAt: "NOW()",
    updatedAt: "NOW()",
    userId: 0,
  },
];

// {
//   id: 0,
//   ltd: 47.205215,
//   lng: 38.945839,
//   desc: "Памятник Петру I",
//   pathId: 1,
//   address: "сквер Петра I",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//   id: 1,
//   ltd: 47.211055,
//   lng: 38.935473,
//   desc: "Дом Третьякова",
//   pathId: 1,
//   address: "ул. Петровская, 43",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//   id: 2,
//   ltd: 47.205019,
//   lng: 38.940387,
//   desc: "Памятник Ю.А. Гагарину и С.П. Королёву",
//   pathId: 1,
//   address: "ул. Чехова, 22",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//   id: 3,
//   ltd: 47.21152,
//   lng: 38.927792,
//   desc: "Памятник Александру I",
//   pathId: 1,
//   address: "ул. Александровская, 68",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//   id: 4,
//   ltd: 47.213956,
//   lng: 38.931951,
//   desc: "Дом Н.В. Кукольника",
//   pathId: 1,
//   address: "пер. Лермонтовский, 5",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//   id: 5,
//   ltd: 47.209176,
//   lng: 38.922762,
//   desc: "Музей А.А. Дурова",
//   pathId: 1,
//   address: "пер. Антона Глушко, 44",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//   id: 6,
//   ltd: 47.215395,
//   lng: 38.921432,
//   desc: "Гимназия №2 имени А.П. Чехова",
//   pathId: 1,
//   address: "ул. Октябрьская, 9",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//   id: 7,
//   ltd: 47.215988,
//   lng: 38.918063,
//   desc: "Музей Лавка Чеховых",
//   pathId: 1,
//   address: "ул. Александровская, 100",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//   id: 8,
//   ltd: 47.206874,
//   lng: 38.931242,
//   desc: "Домик Чехова",
//   pathId: 1,
//   address: "ул. Чехова, 69",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//   id: 9,
//   ltd: 47.209775,
//   lng: 38.925528,
//   desc: "Дом-музей писателя И.Д. Василенко",
//   pathId: 1,
//   address: "ул. Чехова, 88",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//   id: 10,
//   ltd: 47.210773,
//   lng: 38.933793,
//   desc: "Дом Ф.Г. Раневской",
//   pathId: 1,
//   address: "ул. Фрунзе, 10",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//     id: 11,
//     ltd: 47.221221,
//     lng: 38.914614,
//     desc: "Памятник-символ Паровоз",
//     pathId: 2,
//     address: "площадь Восстания, 1",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 12,
//     ltd: 47.222910,
//     lng: 38.934197,
//     desc: "Таганрогский военно-исторический музей",
//     pathId: 2,
//     address: "ул. Лесная Биржа, 20Б",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 13,
//     ltd: 47.213534,
//     lng: 38.928277,
//     desc: "Дворец Н.Д. Алфераки",
//     pathId: 2,
//     address: "ул. Фрунзе, 41",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 14,
//     ltd: 47.269734,
//     lng: 39.334211,
//     desc: "Археологический музей-заповедник Танаис",
//     pathId: 2,
//     address: " Мясниковский район, хутор Недвиговка",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 15,
//     ltd: 47.218583,
//     lng: 38.921109,
//     desc: "музей градостроительства и быта города Таганрога",
//     pathId: 2,
//     address: "ул. Фрунзе, 80",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
// {
//     id: 16,
//     ltd: 47.22291,
//     lng: 38.934197,
//     desc: "Таганрогский военно-исторический музей",
//     pathId: 3,
//     address: "ул. Лесная Биржа, 20Б",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 17,
//     ltd: 47.220740,
//     lng: 38.927535,
//     desc: "Памятник Вечный огонь",
//     pathId: 3,
//     address: "Парк Культуры и отдыха имени Горького",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 18,
//     ltd: 47.254948,
//     lng: 38.938377,
//     desc: "Чаша Горечи",
//     pathId: 3,
//     address: "ул. Бабушкина, 6",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 19,
//     ltd: 47.251460,
//     lng: 38.911945,
//     desc: "Памятный камень Аллея Бессметрия",
//     pathId: 3,
//     address: "ул. Пальмиро Тольятти, 26А",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 20,
//     ltd: 47.238808,
//     lng: 38.922531,
//     desc: "Обелиск металлургам, павшим в годы ВОВ",
//     pathId: 3,
//     address: "ул. Заводская, 20/3",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 21,
//     ltd: 47.207243,
//     lng: 38.953043,
//     desc: "Корабль-памятник морякам Азовской флотилии",
//     pathId: 3,
//     address: "площадь Морского Вокзала, 2",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 22,
//     ltd: 47.215371,
//     lng: 38.928602,
//     desc: "Стела Город воинской славы Таганрог",
//     pathId: 3,
//     address: "ул. Петровская, 73",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 23,
//     ltd: 47.215371,
//     lng: 38.928602,
//     desc: "Скульптурная группа участникам Таганрогского комсомольского подполья Клятва Юности",
//     pathId: 3,
//     address: "пер. Спартаковский",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
// {
//   id: 24,
//   ltd: 47.215395,
//   lng: 38.921432,
//   desc: "Гимназия №2 имени А.П. Чехова",
//   pathId: 4,
//   address: "ул. Октябрьская, 9",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//   id: 25,
//   ltd: 47.215988,
//   lng: 38.918063,
//   desc: "Музей Лавка Чеховых",
//   pathId: 4,
//   address: "ул. Александровская, 100",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
// {
//   id: 26,
//   ltd: 47.209176,
//   lng: 38.922762,
//   desc: "Музей А.А. Дурова",
//   pathId: 4,
//   address: "пер. Антона Глушко, 44",
//   review: null,
//   isPrivate: false,
//   createdAt: "NOW()",
//   updatedAt: "NOW()",
//   userId: 0,
// },
//   {
//     id: 27,
//     ltd: 47.222910,
//     lng: 38.934197,
//     desc: "Таганрогский военно-исторический музей",
//     pathId: 4,
//     address: "ул. Лесная Биржа, 20Б",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//     {
//     id: 28,
//     ltd: 47.213534,
//     lng: 38.928277,
//     desc: "Дворец Н.Д. Алфераки",
//     pathId: 4,
//     address: "ул. Фрунзе, 41",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 29,
//     ltd: 47.210179,
//     lng: 38.930721,
//     desc: "Таганрогский художественный музей",
//     pathId: 4,
//     address: "ул. Александровская, 56",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
// {
//     id: 30,
//     ltd: 47.206874,
//     lng: 38.931242,
//     desc: "Домик Чехова",
//     pathId: 5,
//     address: "ул. Чехова, 69",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 31,
//     ltd: 47.215988,
//     lng: 38.918063,
//     desc: "Музей Лавка Чеховых",
//     pathId: 5,
//     address: "ул. Александровская, 100",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 32,
//     ltd: 47.215395,
//     lng: 38.921432,
//     desc: "Гимназия №2 имени А.П. Чехова",
//     pathId: 5,
//     address: "ул. Октябрьская, 9",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 33,
//     ltd: 47.210561,
//     lng: 38.922232,
//     desc: "Памятник А. П. Чехову",
//     pathId: 5,
//     address: "ул. Чехова, 107",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 34,
//     ltd: 47.215864,
//     lng: 38.918189,
//     desc: 'Скульптура "Толстый и тонкий"',
//     pathId: 5,
//     address: "ул. Александровская, 100",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 35,
//     ltd: 47.215437,
//     lng: 38.921802,
//     desc: 'Скульптура "Человек в футляре"',
//     pathId: 5,
//     address: "ул. Октябрьская, 9",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
//   {
//     id: 36,
//     ltd: 47.217595,
//     lng: 38.926167,
//     desc: 'Скульптура "Египетская пирамида"',
//     pathId: 5,
//     address: "пер. Малый Садовый",
//     review: null,
//     isPrivate: false,
//     createdAt: "NOW()",
//     updatedAt: "NOW()",
//     userId: 0,
//   },
